FROM ruby:2.7.5-alpine


ENV BUILD_PACKAGES="vim curl curl-dev ruby-dev build-base bash less" \
    DEV_PACKAGES="zlib-dev libxml2-dev libxslt-dev tzdata yaml-dev sqlite-dev postgresql-dev mysql-dev imagemagick imagemagick-dev imagemagick-c++ ffmpeg py-pip shared-mime-info" \
    RUBY_PACKAGES="ruby-json yaml nodejs npm" \
    LANG=ja_JP.UTF-8 \
    PATH=/root/.yarn/bin:$PATH \
    APP_ROOT=/usr/src/app

### set bundler version ###########################

ENV BUNDLER_VERSION 2.1.4

############################################

### set timezone ###########################

RUN apk --update add tzdata \
 && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
 && apk del tzdata \
 && rm -rf /var/cache/apk/*

############################################

### install packages #######################

RUN apk update \
 && apk upgrade \
 && apk add --update $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES \
 && rm -rf /var/cache/apk/* \
 && /bin/bash

RUN node -v

RUN npm config set unsafe-perm true \
 && npm install --global yarn \
 && mkdir -p $APP_ROOT

############################################

WORKDIR /tmp

### install RubyGems #######################

COPY Gemfile /tmp/Gemfile
COPY Gemfile.lock /tmp/Gemfile.lock
COPY bin /tmp/bin


RUN bundler install
RUN bundle check || bundle install --jobs 5 --retry 5 \
 && bundle clean --force


############################################

WORKDIR $APP_ROOT
COPY . $APP_ROOT

### install node_modules ###################

RUN bin/yarn install && npm rebuild node-sass

############################################

EXPOSE 3000
